export default {
  buttonContainer: {
    marginTop: 22,
    width: 120,
    height: 43,
    backgroundColor: 'rgb(0,0,0)',
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgb(233, 252, 100)',
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '900',
    fontFamily: null,
    color: 'white',
  },
  patreon: {
    marginTop: -14,
    marginBottom: 21,
    height: 32,
    width: 105,
    borderWidth: 0.8,
    padding: 9,
  },
  vipButton: {
    marginTop: 0,
    width: 90,
    marginLeft: 11,
    alignSelf: 'flex-end',
    bottom: -22,
  },
  vipContent: {
    fontSize: 24,
  },
  counter: {
    marginTop: 0,
    marginBottom: 0,
    width: 'auto',
    minWidth: 75,
    borderWidth: 0.5,
    padding: 9,
    height: 32,
  },
};
